### PR TITLE
Improved installation steps

### PR DESCRIPTION
**Pull request by gnugat**
Symfony 2.0 should now only be a nightmare long forgotten, so here's a composer only installation usage. Also I've used the recent `1.0.0` tag, so people won't need to download the internet when running `composer update` (`dev-master` is never cached by Composer).

### CODE REVIEW

**Comment by francisbesset** [comment]
Symfony 2 0 is dead?
I loved Symfony 2.0 as much as all versions of symfony 1 :'(

**Comment by gnugat** [comment]
Dead since september 2013, I'm afraid :( http://symfony.com/roadmap?version=2.0

**Comment by francisbesset** [comment]
Sorry, but I need time to gather myself.

**Comment by francisbesset** [comment]
giphy

**Pull request merged**
